export const GET_MENTORS = 'GET_MENTORS'
export const RECIEVED_GET_MENTORS = 'RECIEVED_GET_MENTORS'
export const FAILURE_GET_MENTORS = 'FAILURE_GET_MENTORS'

export const GET_GROUPS = "GET_GROUPS"
export const RECIEVED_GET_GROUPS = 'RECIEVED_GET_GROUPS'
export const FAILURE_GET_GROUPS = 'FAILURE_GET_GROUPS'

export const CREATE_MENTOR = "CREATE_MENTOR"
export const RECIEVED_NEW_MENTOR = "RECIEVED_NEW_MENTOR"
export const FAILURE_CREATE_MENTOR = 'FAILURE_CREATE_MENTOR'

export const DELETE_MENTOR = "DELETE_MENTOR"
export const SUCCESS_DELETE_MENTOR = "SUCCESS_DELETE_MENTOR"
export const FAILURE_DELETE_MENTOR = 'FAILURE_DELETE_MENTOR'

export const UPDATE_MENTOR = "UPDATE_MENTOR"
export const SUCCESS_UPDATE_MENTOR = "SUCCESS_UPDATE_MENTOR"
export const FAILURE_UPDATE_MENTOR = 'FAILURE_UPDATE_MENTOR'

export const CREATE_GROUP = "CREATE_GROUP"
export const RECIEVED_NEW_GROUP = "RECIEVED_NEW_GROUP"
export const FAILURE_CREATE_GROUP = 'FAILURE_CREATE_GROUP'

export const DELETE_GROUP = "DELETE_GROUP"
export const SUCCESS_DELETE_GROUP = "SUCCESS_DELETE_GROUP"
export const FAILURE_DELETE_GROUP = 'FAILURE_DELETE_GROUP'


export const UPDATE_GROUP = "UPDATE_GROUP"
export const SUCCESS_UPDATE_GROUP = "SUCCESS_UPDATE_GROUP"
export const FAILURE_UPDATE_GROUP = 'FAILURE_UPDATE_GROUP'

export const SEARCH_LESSONS = "SEARCH_LESSONS"
export const SUCCESS_SEARCH_LESSONS = "SUCCESS_SEARCH_LESSONS"
export const FAILURE_SEARCH_LESSONS = 'FAILURE_SEARCH_LESSONS'

export const AUTOCOMPLETE = "AUTOCOMPLETE"
export const SUCCESS_AUTOCOMPLETE = "SUCCESS_AUTOCOMPLETE"
export const FAILURE_AUTOCOMPLETE = 'FAILURE_AUTOCOMPLETE'

export const GET_ACTIVE_GROUPS = "GET_ACTIVE_GROUPS"
export const RECIEVED_ACTIVE_GROUPS = 'RECIEVED_ACTIVE_GROUPS'
export const FAILURE_ACTIVE_GROUPS = 'FAILURE_ACTIVE_GROUPS'

export const GET_ROOMS = "GET_ROOMS"
export const RECIEVED_ROOMS = 'RECIEVED_ROOMS'
export const FAILURE_ROOMS = 'FAILURE_ROOMS'

export const GET_COURSES = "GET_COURSES"
export const RECIEVED_COURSES = 'RECIEVED_COURSES'
export const FAILURE_COURSES = 'FAILURE_COURSES'

export const CREATE_LESSON_IN_WEEK = "CREATE_LESSON_IN_WEEK"
export const RECIEVED_NEW_LESSON_IN_WEEK = "RECIEVED_NEW_LESSON_IN_WEEK"
export const FAILURE_CREATE_LESSON_IN_WEEK = 'FAILURE_CREATE_LESSON_IN_WEEK'

export const UPDATE_LESSON_IN_WEEK = "UPDATE_LESSON_IN_WEEK"
export const SUCCESS_UPDATE_LESSON_IN_WEEK = "SUCCESS_UPDATE_LESSON_IN_WEEK"
export const FAILURE_UPDATE_LESSON_IN_WEEK = 'FAILURE_UPDATE_LESSON_IN_WEEK'

export const DELETE_LESSON_IN_WEEK = "DELETE_LESSON_IN_WEEK"
export const SUCCESS_DELETE_LESSON_IN_WEEK = "SUCCESS_DELETE_LESSON_IN_WEEK"
export const FAILURE_DELETE_LESSON_IN_WEEK = 'FAILURE_DELETE_LESSON_IN_WEEK'

export const CREATE_BUSY_IN_WEEK = "CREATE_BUSY_IN_WEEK"
export const RECIEVED_NEW_BUSY_IN_WEEK = "RECIEVED_NEW_BUSY_IN_WEEK"
export const FAILURE_CREATE_BUSY_IN_WEEK = 'FAILURE_CREATE_BUSY_IN_WEEK'

export const UPDATE_BUSY_IN_WEEK = "UPDATE_BUSY_IN_WEEK"
export const SUCCESS_UPDATE_BUSY_IN_WEEK = "SUCCESS_UPDATE_BUSY_IN_WEEK"
export const FAILURE_UPDATE_BUSY_IN_WEEK = 'FAILURE_UPDATE_BUSY_IN_WEEK'

export const DELETE_BUSY_IN_WEEK = "DELETE_BUSY_IN_WEEK"
export const SUCCESS_DELETE_BUSY_IN_WEEK = "SUCCESS_DELETE_BUSY_IN_WEEK"
export const FAILURE_DELETE_BUSY_IN_WEEK = 'FAILURE_DELETE_BUSY_IN_WEEK'


